# Generated by Django 4.1 on 2023-07-09 16:52

from django.db import migrations, models
import helping.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='disease_knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('its_photo', models.ImageField(blank=True, null=True, upload_to=helping.models.disease_knowledge_upload)),
                ('name', models.CharField(max_length=150)),
                ('desciption', models.TextField(max_length=1000)),
                ('treatment', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='first_aid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('its_photo', models.ImageField(blank=True, null=True, upload_to=helping.models.first_aid_upload)),
                ('name', models.CharField(max_length=150)),
                ('desciption', models.TextField(max_length=1000)),
                ('treatment', models.TextField(max_length=1000)),
            ],
        ),
    ]
