# Generated by Django 4.1 on 2023-02-23 08:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import nurses.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('his_photo', models.ImageField(blank=True, null=True, upload_to=nurses.models.nurse_photo_upload)),
                ('his_name', models.CharField(max_length=100)),
                ('his_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(200)])),
                ('his_hospital', models.CharField(max_length=25)),
                ('his_degree', models.ImageField(blank=True, null=True, upload_to=nurses.models.nurse_degree_photo_upload)),
                ('his_email_for_connect', models.EmailField(default='Notfound', max_length=254)),
                ('his_number_for_connect', models.CharField(default='Notfound', max_length=11)),
                ('his_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurses.city')),
                ('his_governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurses.governorate')),
                ('his_specialty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nurses.specialty')),
            ],
        ),
    ]
