# Generated by Django 4.1 on 2023-03-09 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0002_nurse_his_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='his_specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurses.specialty'),
        ),
    ]
