# Generated by Django 4.1 on 2023-05-05 06:54

import django.core.validators
from django.db import migrations, models
import nurses.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('his_photo', models.ImageField(blank=True, null=True, upload_to=nurses.models.nurse_photo_upload)),
                ('his_name', models.CharField(max_length=100)),
                ('his_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(200)])),
                ('his_sex', models.CharField(choices=[('ذكر', 'ذكر'), ('انثي', 'انثي')], default='Notfound', max_length=15)),
                ('his_governorate', models.CharField(max_length=100)),
                ('his_city', models.CharField(max_length=100)),
                ('his_specialty', models.CharField(max_length=100)),
                ('his_hospital', models.CharField(max_length=25)),
                ('his_email_for_connect', models.EmailField(default='Notfound', max_length=254)),
                ('his_number_for_connect', models.CharField(default='Notfound', max_length=11)),
                ('his_facebook_account', models.URLField()),
                ('his_instagram_account', models.URLField()),
                ('his_twitter_account', models.URLField()),
            ],
        ),
    ]
