# Generated by Django 4.1 on 2023-07-04 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_remove_profile_bio_profile_age_profile_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illnesses_numbers', models.IntegerField(blank=True, null=True)),
                ('illnesses', models.CharField(blank=True, max_length=30, null=True)),
                ('illnesses_descriptions', models.TextField(blank=True, max_length=600, null=True)),
                ('allergies', models.TextField(blank=True, max_length=150, null=True)),
                ('surgeries', models.TextField(blank=True, max_length=150, null=True)),
                ('immunizations', models.TextField(blank=True, max_length=150, null=True)),
                ('results_of_physical_exams_and_tests', models.TextField(blank=True, max_length=150, null=True)),
                ('physical_exams_and_tests_images', models.ImageField(blank=True, null=True, upload_to='medical_images')),
                ('medicines', models.TextField(blank=True, max_length=150, null=True)),
                ('medicines_images', models.ImageField(blank=True, null=True, upload_to='medical_images')),
                ('medical_rays', models.TextField(blank=True, max_length=150, null=True)),
                ('medical_rays_images', models.ImageField(blank=True, null=True, upload_to='medical_images')),
                ('health_habits', models.TextField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
