# Generated by Django 4.1 on 2023-07-04 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_medicalhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='health_habits',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='illnesses',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='illnesses_descriptions',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='illnesses_numbers',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='immunizations',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='medical_rays',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='medical_rays_images',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='medicines',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='medicines_images',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='physical_exams_and_tests_images',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='results_of_physical_exams_and_tests',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='surgeries',
        ),
    ]
