# Generated by Django 4.1 on 2023-07-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_medicalhistory_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allergies',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='health_habits',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='illnesses',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='illnesses_descriptions',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='illnesses_numbers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='immunizations',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='medical_rays',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='medical_rays_images',
            field=models.ImageField(blank=True, null=True, upload_to='medical_images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='medicines',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='medicines_images',
            field=models.ImageField(blank=True, null=True, upload_to='medical_images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='physical_exams_and_tests_images',
            field=models.ImageField(blank=True, null=True, upload_to='medical_images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='results_of_physical_exams_and_tests',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='surgeries',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
