# Generated by Django 4.1 on 2023-02-21 09:55

from django.db import migrations, models
import django.db.models.deletion
import doctor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('his_photo', models.ImageField(blank=True, null=True, upload_to=doctor.models.doctor_photo_upload)),
                ('his_name', models.CharField(max_length=25)),
                ('his_age', models.IntegerField(max_length=3)),
                ('his_clinic_name', models.CharField(max_length=15)),
                ('his_clinic_location', models.CharField(max_length=25)),
                ('his_clinic_number', models.CharField(max_length=11)),
                ('his_clinic_start_at', models.IntegerField(max_length=2)),
                ('his_clinic_finsh_at', models.IntegerField(max_length=2)),
                ('his_clinic_price', models.IntegerField(max_length=4)),
                ('his_email_for_connect', models.EmailField(default='Notfound', max_length=254)),
                ('his_number_for_connect', models.CharField(default='Notfound', max_length=11)),
                ('his_city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.city')),
                ('his_governorate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.governorate')),
                ('his_specialty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.specialty')),
            ],
        ),
    ]
