# Generated by Django 4.1 on 2023-02-21 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctor_his_clinic_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='his_governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.governorate'),
        ),
    ]
