# Generated by Django 4.1 on 2023-02-21 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_doctor_his_governorate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='his_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.city'),
        ),
    ]
