# Generated by Django 4.1 on 2023-02-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_doctor_his_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='cit_filter',
            field=models.CharField(default='الزقازيق', max_length=25),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty_filter',
            field=models.CharField(default='قلب', max_length=25),
        ),
    ]
