# Generated by Django 4.1 on 2023-02-27 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_doctor_cit_filter_doctor_specialty_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='his_specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.specialty'),
        ),
    ]
