# Generated by Django 4.1 on 2023-06-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_alter_doctor_his_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='cit_filter',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialty_filter',
        ),
    ]
